# [[SystemFS.Mount]]
# This type of entry mounts a device to a VFS node
# FileSystem="<device name>"
# Path="<some path to a node>"

# [[NetworkInterface]]
# DeviceName="<device name, e.g. eth0>"
# LocalIP="<some IP>"
# Netmask="<some IP mask>"
# Gateway="<some IP>"

# [[Run]]
# This type of entry runs an executable at startup
# Path="<path to an executable>"

[General]
# Force a monotask system, but a lot of things won't work (network, task & process termination, ...)
# Mono=1
# Force a quantum time using the entry below
# QuantumMS=10
# Override deferred work timings
# DeferredWorkWaitTimeoutMS=50
# DeferredWorkPollDelayMS=5
# Force polling (default is 0 for interrupts)
# Polling=1
# Configure the number of device interrupt slots (1-32)
# DeviceInterruptSlots=32
# Enable or disable login sequence (1=enable, 0=disable)
# DoLogin=1

[Task]
# Specify minimum size for a task's stack
MinimumTaskStackSize=65536
# Specify minimum size for a task's system stack (interrupts, syscalls)
MinimumSystemStackSize=16384

[KernelPath]
# Logical kernel file/folder paths.
UsersDatabase="/system/data/users.database"
KeyboardLayouts="/system/keyboard"
UsersRoot="/users"
CurrentUserAlias="/current-user"
PrivatePackageAlias="/package"
PrivateUserDataAlias="/user-data"

[[SystemFS.Mount]]
FileSystem="active"
SourcePath="exos"
Path="/system"

[[SystemFS.Mount]]
FileSystem="active"
SourcePath="exos/users"
Path="/users"

[[SystemFS.Mount]]
FileSystem="active"
SourcePath="exos/apps"
Path="/apps"

[[SystemFS.Mount]]
FileSystem="active"
SourcePath="exos/temp"
Path="/temp"

[[SystemFS.Mount]]
FileSystem="active"
SourcePath="exos/scripts"
Path="/scripts"

[Keyboard]
# Available layouts : de-DE, en-US, fr-FR
Layout="en-US"

[Network]
# Global network configuration (fallback values)
UseDHCP=1
LocalIP="10.0.2.15"
Netmask="255.255.255.0"
Gateway="10.0.2.2"
DefaultPort=8080

[[NetworkInterface]]
# Configuration for first E1000 device
DeviceName="eth0"
LocalIP="192.168.56.10"

[TCP]
# TCP configuration
EphemeralPortStart=32768
SendBufferSize=32768
ReceiveBufferSize=32768

# Run section (specify an executable to run)
# [[Run]]
# Command="/system/APPS/PORTAL"
# Command="/system/APPS/HELLO"
